"""create_baseline_schema

Revision ID: 33c59e6e1b19
Revises: fe43f18f40f2
Create Date: 2025-08-18 18:56:10.415439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c59e6e1b19'
down_revision: Union[str, None] = 'fe43f18f40f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
