"""add pre_grading_workflows table

Revision ID: fe43f18f40f2
Revises: 
Create Date: 2025-07-31 21:47:42.094177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe43f18f40f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_grading_workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exam_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('statistics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_grading_workflows_exam_id'), 'pre_grading_workflows', ['exam_id'], unique=False)
    op.create_index(op.f('ix_pre_grading_workflows_id'), 'pre_grading_workflows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pre_grading_workflows_id'), table_name='pre_grading_workflows')
    op.drop_index(op.f('ix_pre_grading_workflows_exam_id'), table_name='pre_grading_workflows')
    op.drop_table('pre_grading_workflows')
    # ### end Alembic commands ###
